config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  root 'welcome#index'
  resources :about_us
  resources :cardapio
  resources :delivery
  resources :orders

  resources :pizzas, only: [:show, :index]
  resources :sizes, only: [:show, :index]

namespace :admin do
  resources :pizzas
  resources :sizes
end


end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :size 
end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
	validates :name, presence: true
	validates :description, presence: true
	validates :price, presence: true

	mount_uploader :image, ImageUploader
end

app/models/size.rb
class Size < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
	def index
		
	end
end

app/controllers/admin/pizzas_controller.rb
class Admin::PizzasController < AdminController
	
	before_action :set_pizza, only: [:show, :edit, :update, :destroy]

	def index
		#@pizzas = Pizza.order('name').page(params[:page])
		@q = Pizza.ransack(params[:q])
		@pizzas = @q.result
	end

	def show
		
	end

	def new
		@pizza = Pizza.new		
	end

	def create
		@pizza = Pizza.new(pizza_params)

		if @pizza.save
			redirect_to admin_pizzas_path, notice: "A pizza foi cadastrada com sucesso!"
		else
			render :new			
		end
	end

	def edit
		
	end

	def update
		if @pizza.update(pizza_params)
			redirect_to admin_pizzas_path, notice: "A pizza foi atualizada com sucesso!"
		else
			render :edit
		end
	end

	def destroy
		@pizza.destroy
		redirect_to admin_pizzas_path, notice: "A pizza foi excluida com sucesso!"		
	end

	private
	def set_pizza
		@pizza = Pizza.find(params[:id])		
	end

	def pizza_params
		params.require(:pizza).permit(:name, :description, :price, :image)		
	end
end

app/controllers/admin/sizes_controller.rb
class Admin::SizesController < AdminController

	before_action :set_size, only: [:show, :edit, :update, :destroy]

	def index
		#@sizes = Size.all
		@q = Size.ransack(params[:q])
		@sizes = @q.result
	end

	def show
		
	end

	def new
		@size = Size.new		
	end

	def create
		@size = Size.new(size_params)

		if @size.save
			redirect_to admin_sizes_path, notice: "A pizza foi cadastrada com sucesso!"
		else
			render :new			
		end
	end

	def edit
		
	end

	def update
		if @size.update(size_params)
			redirect_to admin_sizes_path, notice: "A pizza foi atualizada com sucesso!"
		else
			render :edit
		end
	end

	def destroy
		@size.destroy
		redirect_to admin_sizes_path, notice: "A pizza foi excluida com sucesso!"		
	end

	private
	def set_size
		@size = Size.find(params[:id])		
	end

	def size_params
		params.require(:size).permit(:name, :slices_number)		
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  #layout 'admin'	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cardapio_controller.rb
class CardapioController < ApplicationController

	before_action :set_pizza, only: [:show, :edit, :update, :destroy]

	def index
		@pizzas = Pizza.order('name').page(params[:page])
	end

	def new
		@pizza = Pizza.new		
	end

	def show
		
	end

	def create
		@pizza = Pizza.new(pizza_params)

		if @pizza.save
			redirect_to pizzas_path, notice: "A pizza foi cadastrada com sucesso!"
		else
			render :new			
		end
	end

	def edit
		
	end

	def update
		if @pizza.update(pizza_params)
			redirect_to pizzas_path, notice: "A pizza foi atualizada com sucesso!"
		else
			render :edit
		end
	end

	def destroy
		@pizza.destroy
		redirect_to pizzas_path, notice: "A pizza foi excluida com sucesso!"		
	end

	private
	def set_pizza
		@pizza = Pizza.find(params[:id])		
	end

	def pizza_params
		params.require(:pizza).permit(:name, :description, :price, :image)		
	end

end

app/controllers/delivery_controller.rb
class DeliveryController < ApplicationController

	before_action :set_order, only: [:show, :edit, :update, :destroy]

	def index
		@orders = Order.all
	end

	def new
		@order = Order.new
	end

	def create
		@order = Order.new(order_params)

		if @order.save
			redirect_to delivery_path, notice: 'O cliente foi cadastrado com sucesso!'
		else
			render :new
		end
		
	end

	def edit
		
	end

	def update
		if @order.update(order_params)
			redirect_to delivery_path, notice: 'O cliente foi atualizado com sucesso!'
		else
			render :edit
		end
		
	end

	def destroy
		@order.destroy
		redirect_to delivey_path, notice: 'O cliente foi excluido com sucesso!'
	end

	private
	def set_order
		@order = Order.find(params[:id])
	end

	def order_params
		params.require(:order).permit(:border)		
	end
	
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :set_order, only: [:show, :edit, :update, :destroy]

	def index
		@orders = Order.all
	end

	def new
		@order = Order.new
	end

	def create
		@order = Order.new(order_params)

		if @order.save
			redirect_to delivery_path, notice: 'O cliente foi cadastrado com sucesso!'
		else
			render :new
		end
		
	end

	def edit
		
	end

	def update
		if @order.update(order_params)
			redirect_to delivery_path, notice: 'O cliente foi atualizado com sucesso!'
		else
			render :edit
		end
		
	end

	def destroy
		@order.destroy
		redirect_to delivey_path, notice: 'O cliente foi excluido com sucesso!'
	end

	private
	def set_order
		@order = Order.find(params[:id])
	end

	def order_params
		params.require(:order).permit(:border)		
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		
	end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cardapio_helper.rb
module CardapioHelper
end

app/helpers/delivery_helper.rb
module DeliveryHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/size_helper.rb
module SizeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about_us/index.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title text-center">Quem Somos?</h3>
  </div>
  <div class="panel-body">
    <div class="text-justify well">
      <p> Mussum Ipsum, cacilds vidis litro abertis. Cevadis im ampola pa arma uma pindureta. Viva Forevis aptent taciti sociosqu ad litora torquent Quem manda na minha terra sou Euzis! Interagi no mé, cursus quis, vehicula ac nisi. </p>
      <p> Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose. Suco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis. in elementis mé pra quem é amistosis quis leo. Si u mundo tá muito paradis? Toma um mé que o mundo vai girarzis! </p>
      <p> Atirei o pau no gatis, per gatis num morreus. Pra lá , depois divoltis porris, paradis. Ta deprimidis, eu conheço uma cachacis que pode alegrar sua vidis.” </p>
    </div>
  </div>
</div>

app/views/admin/pizzas/_form.html.erb
<%= simple_form_for [:admin, @pizza], :html => { :class => 'form-vertical' } do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :image %>

  
  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_pizzas_path, :class => 'btn btn-default' %>
<% end %>

app/views/admin/pizzas/index.html.erb
<%- model_class = Pizza -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<div>
  <div class="pull-right">
    <%= search_form_for [:admin, @q] do |f| %>
      <%= f.label :name %>
      <%= f.search_field :name_cont %>
      <%= f.submit %>
    <% end %>
  </div>

  <div>
    <%= link_to t('.new', :default => t("helpers.links.new")), new_admin_pizza_path, :class => 'btn btn-primary' %> 
  </div>
</div>

<div class="table-responsive">
<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= sort_link(@q, :name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= sort_link(@q, :price) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pizzas.each do |pizza| %>
      <tr>
        <td><%= pizza.id%></td>
        <td><%= pizza.name %></td>
        <td><%= pizza.description %></td>
        <td><%= pizza.price %></td>
        <td><%= image_tag pizza.image, size:"120" %></td>
        <td><%=l pizza.created_at %></td>
        <td><%=l pizza.updated_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_pizza_path(pizza), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_pizza_path(pizza),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/admin/pizzas/new.html.erb
<%- model_class = Pizza -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/pizzas/show.html.erb
<%- model_class = Pizza -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @pizza.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @pizza.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @pizza.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= image_tag @pizza.image, size: '300x300' %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              pizzas_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_pizza_path(@pizza), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              pizza_path(@pizza),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/admin/sizes/_form.html.erb
<%= simple_form_for [:admin, @size], :html => { :class => 'form-vertical' } do |f| %>
  <%= f.input :name %>
  <%= f.input :slices_number %>
  
  
  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_sizes_path, :class => 'btn btn-default' %>
<% end %>

app/views/admin/sizes/edit.html.erb
<%- model_class = Size -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/sizes/index.html.erb
<%- model_class = Size -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<div>
  <div class="pull-right">
    <%= search_form_for [:admin, @q] do |f| %>
      <%= f.label :name %>
      <%= f.search_field :name_cont %>
      <%= f.submit %>
    <% end %>
  </div>

  <div>
    <%= link_to t('.new', :default => t("helpers.links.new")), new_admin_size_path, :class => 'btn btn-primary' %> 
  </div>
</div>

<div class="table-responsive">
<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= sort_link(@q, :name) %></th>
      <th><%= model_class.human_attribute_name(:slices_number) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sizes.each do |size| %>
      <tr>
        <td><%= size.id%></td>
        <td><%= size.name %></td>
        <td><%= size.slices_number %></td>
        <td><%=l size.created_at %></td>
        <td><%=l size.updated_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_size_path(size), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_size_path(size),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/admin/sizes/new.html.erb
<%- model_class = Size -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/sizes/show.html.erb
<%- model_class = Size -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @size.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:slices_number) %>:</strong></dt>
  <dd><%= @size.slices_number %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              size_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_size_path(@size), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              size_path(@size),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/cardapio/index.html.erb
<div class="panel panel-info">
	<div class="panel-heading">
    	<h3 class="panel-title text-center">Cardapio</h3>
  	</div>
<div class="panel-body">

	
<% @pizzas.each do |c| %>

  <div class="media">   		
      
      <figure class="pull-left">
      	<%= image_tag c.image, size:"120" %>
    	</figure>
  		
      <div class="media-body well">
    		<h4 class="media-heading"> <%= c.name.capitalize %> </h4>
    		
        <p> <%= c.description %> </p> 
        
        <p> Preco:   <%= number_to_currency(c.price) %> </p>
  		</div>
	
  </div>

<% end %>
<%= paginate @pizzas %>

</div>
</div>

app/views/delivery/_form.html.erb
<div class="panel panel-info">
	<div class="panel-heading">
		<h3 class="panel-title text-center">Delivery</h3>
	</div>

	<div class="panel-body">
		<h3 class="text-center">Como deseja sua pizza?</h2>

		<div class="panel panel-primary">
			<div class="panel-heading">
				<h4>Tamanho</h3>
			</div>

			<div class="panel-body">
				<%= simple_form_for @order, :html => { :class => 'form-vertical' } do |f| %>
				
				<%= f.association :size, label: false, as: :radio_buttons, collection: Size.all.order(name: :asc).map {|m| [m.name, m.id]} %>

				<% end %>
			</div>
		</div>
				<%= simple_form_for @order, :html => { :class => 'form-vertical' } do |f| %>
				<%= f.input :border%>
				<% end %>
	</div>
</div>
<!--<%= simple_form_for @order, :html => { :class => 'form-vertical' } do |f| %>
  <%= f.input :border %>
  <%= f.association :size, as: :check_boxes, collection: Size.all.order(name: :asc).map {|m| [m.name, m.id]} %>
  -->

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_pizzas_path, :class => 'btn btn-default' %>
<!--<% end %>

app/views/delivery/edit.html.erb
<%- model_class = Pizza -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/delivery/index.html.erb
<div class="panel panel-info">
	<div class="panel-heading">
		<h3 class="panel-title text-center">Delivery</h3>
	</div>

	<div class="panel-body">
		<h3 class="text-center">Como deseja sua pizza?</h2>

		<div class="panel panel-primary">
			<div class="panel-heading">
				<h4>Tamanho</h3>
			</div>

			<div class="panel-body">
				
				

			</div>
		</div>
	</div>
</div>

app/views/delivery/new.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/delivery/show.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @order.size.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:border) %>:</strong></dt>
  <dd><%= @order.border %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              pizzas_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_pizza_path(@pizza), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              pizza_path(@pizza),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/welcome/index.html.erb
<div class="jumbotron" style="background-image: url(http://www.tarantinos-regensburg.de/wp-content/uploads/2014/08/tarantinos-regensburg-pizzeria-pizza_4.jpg); background-size: cover;">
  <div class="container">
    <span class="text-white text-center"><h1>Pizzaria X</h1></span> 
  </div>
</div>

<div class="row">
	<div class="col-sm-6 col-md-6">
		<div class="bs-example">
    		<div id="myCarousel" class="carousel slide" data-ride="carousel">
        		<ol class="carousel-indicators">
            		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            		<li data-target="#myCarousel" data-slide-to="1"></li>
            		<li data-target="#myCarousel" data-slide-to="2"></li>
        		</ol>   
        		<div class="carousel-inner">
            		<div class="item active">
                		<%= image_tag("pizza.jpg") %>
            		</div>
            		<div class="item">
                		<%= image_tag("pizza2.jpg") %>
            		</div>
            		<div class="item">
                		<%= image_tag("pizza.jpg") %>
            		</div>
        		</div>
        		<a class="carousel-control left" href="#myCarousel" data-slide="prev">
            		<span class="glyphicon glyphicon-chevron-left"></span>
        		</a>
        		<a class="carousel-control right" href="#myCarousel" data-slide="next">
            		<span class="glyphicon glyphicon-chevron-right"></span>
        		</a>
    		</div>
		</div>
	</div>

	<div class="col-sm-6 col-md-6">
		<div class="bs-example">
    		<div id="myCarousel" class="carousel slide" data-ride="carousel">
        		<ol class="carousel-indicators">
            		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            		<li data-target="#myCarousel" data-slide-to="1"></li>
            		<li data-target="#myCarousel" data-slide-to="2"></li>
        		</ol>   
        		<div class="carousel-inner">
            		<div class="item active">
                		<%= image_tag("pizza.jpg") %>
            		</div>
            		<div class="item">
                		<%= image_tag("pizza2.jpg") %>
            		</div>
            		<div class="item">
                		<%= image_tag("pizza.jpg") %>
            		</div>
        		</div>
        		<a class="carousel-control left" href="#myCarousel" data-slide="prev">
            		<span class="glyphicon glyphicon-chevron-left"></span>
        		</a>
        		<a class="carousel-control right" href="#myCarousel" data-slide="next">
            		<span class="glyphicon glyphicon-chevron-right"></span>
        		</a>
    		</div>
		</div>
	</div>
	
</div>